### ISSUE TITLE
About common/rela.py & routing_transformer.py & linearattention.py

### ISSUE THREAD

**Issue by Z-Z-J** [JinluZhang1126/MixSTE#14]
![QQ截图20221018162655](https://user-images.githubusercontent.com/53818279/196378182-61edf294-f989-4e7a-9b4d-9d2909ef1a81.png)
Can you provide these files ?

**Comment by JinluZhang1126** [comment]
> ![QQ截图20221018162655](https://user-images.githubusercontent.com/53818279/196378182-61edf294-f989-4e7a-9b4d-9d2909ef1a81.png) Can you provide these files ?

These files are conducted from other works, which mainly focus on decreasing the computation cost of Transformer. They do not affect the results of the model. We only use them to test the effects of our work.

If you have interest in it, please pay attention to these works:
- Informer: Beyond Efficient Transformer for Long Sequence Time-Series Forecasting;
- Reformer: The Efficient Transformer
- Linformer: Self-Attention with Linear Complexity
