### ISSUE TITLE
Joint Separation

### ISSUE THREAD

**Issue by nies14** [JinluZhang1126/MixSTE#20]
Hi, thanks for the great work. Could you please say/point out where you are separating the joint in the code?

**Comment by bigrayss** [comment]
I believe that in poseformer's temporal block, x.shape=(b, f, c*n), while in this work, x.shape=(b*n, f, c). The transformer works in (f, c*n) and (f, c), so he does separate the joints.

**Comment by nies14** [comment]
> I believe that in poseformer's temporal block, x.shape=(b, f, c_n), while in this work, x.shape=(b_n, f, c). The transformer works in (f, c*n) and (f, c), so he does separate the joints.

I got your point. Thanks for the help.
