### ISSUE TITLE
ModuleNotFoundError: No module named 'common.h36m_dataset'

### ISSUE THREAD

**Issue by 2455DD** [JinluZhang1126/MixSTE#32]
The code can't run with the error `ModuleNotFoundError: No module named 'common.h36m_dataset'`

My command is `python run.py -k cpn_ft_h36m_dbb -f 243 -s 243 -drop 0.1 -e 160 -l log/train -c checkpoint -gpu 0,1 --export-training-curves`.

The traceback stack shown below
```
Traceback (most recent call last):
  File "run.py", line 88, in <module>
    from common.h36m_dataset import Human36mDataset
ModuleNotFoundError: No module named 'common.h36m_dataset'
```

**Comment by 2455DD** [comment]
It seems that all .py files under `data` folder (or "module") should be moved to `common`

**Comment by JinluZhang1126** [comment]
> It seems that all .py files under `data` folder (or "module") should be moved to `common`

Yes, sorry for that, and I have modified it in the latest version. Thanks for your reply.
