### ISSUE TITLE
Checkpoints download issue

### ISSUE THREAD

**Issue by tomik125** [JinluZhang1126/MixSTE#34]
Thank you for sharing the code, however, I can't download the checkpoints from Baidu.

Could you share the checkpoints somewhere else (GoogleDrive, Onedrive, ...)?

Thanks.

**Comment by 2455DD** [comment]
check this https://drive.google.com/file/d/1bkAUjPIvsmsRXgKr-GCJtPum3K-It3-l/view?usp=sharing

**Comment by tomik125** [comment]
Thanks perfect!
