### ISSUE TITLE
About batch size (1024)

### ISSUE THREAD

**Issue by shawnpark07** [JinluZhang1126/MixSTE#4]
Hello, thanks for your impressive work :)

While comprehending your work, here comes one ambiguity.

As you know, H36M train dataset has total 1,559,752 frames, and these would be grouped into 6,716 sequences (243 frames / sequence).
But if we choose batch size of 1,024 as mentioned in the paper, there would be only 6~7 batches per one epoch.

Did I understand right? If so, I think the training would be very unstable due to small number of batches per epoch.
Will looking forward to your answer. Thanks!

**Comment by JinluZhang1126** [comment]
> 

Hi, 1024 means frame numbers of each batch, we apply stride sample to separate 1024 into 5 periods, therefore the overall iterations will be about 1300 in our code.

**Comment by flyyyyer** [comment]
@shawnpark07 Could you reproduce this? 
@JinluZhang1126 How the 1300 can be caclulated? Or you provide the generator.py (ChunkedGenerator_Seq and UnchunkedGenerator_Seq)?

**Comment by Aerikervalid** [comment]
If I increase batchsize does that mean the effect is increased and the model is more stable，But the large bachsize was worse in several experiments. Why do the authors think this is?
