### ISSUE TITLE
Joint Separation in framework

### ISSUE THREAD

**Issue by wenwen12321** [JinluZhang1126/MixSTE#7]
Hi author~
Thanks for your excellent work.
I saw the two versions of your framework figure and just confused about which one is correct actually.

The first one placed **Joint Separation** after **Temporal Position Embedding**, while the other placed **Joint Separation** before**Temporal Position Embedding**.

![image](https://user-images.githubusercontent.com/55979129/182568914-a2b006aa-619f-4750-b35a-2e45cb2fb0cf.png)

![image](https://user-images.githubusercontent.com/55979129/182564494-01422a9b-5370-42eb-afd9-87fc34af2475.png)

btw I also wanna know how to split the dimension to achieve your Separation Joint part?
In my implementation, I rearrange(x, '(b f) p c -> (b p) f c ', f=f) before pass into Temporal Encoder, is that correct??

**Comment by JinluZhang1126** [comment]
> Hi author~ Thanks for your excellent work. I saw the two versions of your framework figure and just confused about which one is correct actually.
> 
> The first one placed **Joint Separation** after **Temporal Position Embedding**, while the other placed **Joint Separation** before**Temporal Position Embedding**.
> 
> ![image](https://user-images.githubusercontent.com/55979129/182568914-a2b006aa-619f-4750-b35a-2e45cb2fb0cf.png)
> 
> ![image](https://user-images.githubusercontent.com/55979129/182564494-01422a9b-5370-42eb-afd9-87fc34af2475.png)
> 
> btw I also wanna know how to split the dimension to achieve your Separation Joint part? In my implementation, I rearrange(x, '(b f) p c -> (b p) f c ', f=f) before pass into Temporal Encoder, is that correct??

Hi, the second figure is correct, because the joint separation is conducted before the temporal attention.
And your operation is correct, but please keep original order of tensor, I suggest using einops rather than reshape function.

**Comment by wenwen12321** [comment]
> > Hi author~ Thanks for your excellent work. I saw the two versions of your framework figure and just confused about which one is correct actually.
> > The first one placed **Joint Separation** after **Temporal Position Embedding**, while the other placed **Joint Separation** before**Temporal Position Embedding**.
> > ![image](https://user-images.githubusercontent.com/55979129/182568914-a2b006aa-619f-4750-b35a-2e45cb2fb0cf.png)
> > ![image](https://user-images.githubusercontent.com/55979129/182564494-01422a9b-5370-42eb-afd9-87fc34af2475.png)
> > btw I also wanna know how to split the dimension to achieve your Separation Joint part? In my implementation, I rearrange(x, '(b f) p c -> (b p) f c ', f=f) before pass into Temporal Encoder, is that correct??
> 
> Hi, the second figure is correct, because the joint separation is conducted before the temporal attention. And your operation is correct, but please keep original order of tensor, I suggest using einops rather than reshape function.

Thanks for your prompt reply!
